services:
  db:
    image: mysql/mysql-server:latest
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_DATABASE=estudie_backend
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_ROOT_HOST=% 
    ports:
      - '3306:3306'
    networks:
      - laravel
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - db

networks:
  laravel:

volumes:
  mysql-volume:
    driver: local
